### ISSUE TITLE
Arguments in Lisp version of python functions are in different order

### ISSUE THREAD

**Issue by rpgoldman** [digikar99/py4cl2#12]
Here's an example of a python function I wrote:

```
def pull_registry(
    root_url: str = "https://foo.bar.com/api",
    debug: bool = False,
    auth: Optional[Dict[str, str]] = None,
) 
```

Here is what using `defpymodule` gives me:

```
 (DEFUN RC::PULL-REGISTRY
                       (
                        &OPTIONAL (RC::AUTH "None") (RC::DEBUG 'NIL)
                        (RC::ROOT-URL "https://bbn-ui.logx.cloud/api/v4"))
```

It looks suspiciously like PY4CL2 has alphabetized these arguments.  At any rate, this is simply unusable.

I am sorry to seem like a troll, but I switched from PY4CL to PY4CL2 because the former was no longer maintained. But there seem to be problems with PY4CL2 that come from an overly ambitious rewrite, in which far too much has simply been thrown away and replaced by new code that is more complicated and has not been sufficiently tested.  Shuffling the argument order absolutely should not be happening here.

Looking at the lisp code, I can see that the `OrderedDict` on the python side has been replaced by a simple `dict`, allowing for the parameters to be shuffled.  It is quite painfully clear that this should be an ordered structure -- probably a lisp association list -- and *not* an unordered structure like a hash table.  This really shakes my confidence in Py4cl2.

**Comment by digikar99** [comment]
> alphabetized these arguments

This should be fixed with the recent commits: https://github.com/digikar99/py4cl2/blob/75d3aab2cb0ae9af56a8fccb081594e931914232/src/arg-list.lisp#L105 (thanks for the earlier issue!)

> troll

No, you aren't. You just might be the first extensive user for py4cl2. Although, I've been using and fixing it, these things hadn't been caught so far.

> PY4CL to PY4CL2

If it works for you, I could back port the changes that lets py4cl2 work on windows but not py4cl. The change of argument lists makes a rewrite necessary for most systems doing the switch. Plus, 5 years down the line, I'm gonna wonder if I should have made the smallish changes, my opinion is "break it now than wonder later".
