### ISSUE TITLE
Digesting message one at a time

### ISSUE THREAD

**Issue by jcguu95** [digikar99/py4cl2#20]
### Problem Description

While the user sends requests to a busy python process `*python*`, a sequence of simple-errors (unhandled message type) will follow. It makes the python process unusable, and I have to `(pystop) (pystart)` to recover. 

This issue has been present in `py4cl`.

### Steps to Reproduce

This can be reproduced by evaluating `(pyeval "time.sleep(5)")` consecutively multiple times using lisp threads. After resolving the error manually, try `(pyeval "1+1")`, which likely will not work. This should be pretty common for `sly` users who are used to fire lisp forms in an emacs buffer

### Proposed Solution

Before sending a request to python, lisp needs to check if python is busy. If so, lisp should wait and try again later.

A more advanced option is to implement multiprocesses. In such case, we should at use bidirectional sockets instead of uni-directional pipes.

### Help Wanted?

If help is needed, I'm willing to. Please let me know.

**Comment by digikar99** [comment]
The following should work as expected now:

```lisp
CL-USER> (dotimes (i 5)
           (bt:make-thread (lambda ()
                             (py4cl2:pyeval "time.sleep(1)"))))
NIL
CL-USER> (py4cl2:pyeval 2)
2
```

---

> A more advanced option is to implement multiprocesses. In such case, we should at use bidirectional sockets instead of uni-directional pipes.

I'll be curious about the advantages and disadvantages (memory?) of multiprocessing. I myself have only a naive idea about threads and processes, so any inputs will be appreciated!

On the other hand, if you are looking to extract performance out of py4cl2, this doesn't seem like a great way out. With my CPU i7-8750H locked to 1GHz, I get an abysmal performance of:

```lisp
CL-USER> (time (loop repeat 10000 do (py4cl2:pyeval "str(1)")))
Evaluation took:
  1.188 seconds of real time
  0.642387 seconds of total run time (0.393231 user, 0.249156 system)
  54.04% CPU
  20,000 forms interpreted
  2,623,059,242 processor cycles
  7,491,744 bytes consed
NIL
```

I have attempted and failed to optimize this in the past, with the results being that almost 90% of the time is spent in stream communication - merely calling `eval` on the python's side can be done at the rate of about a 100000 per second, which is 10 times as much as the above approach.

The simpler way to work around the limitations could be to batch the computations on the python side, so that the time consumed by stream-communication and `eval` becomes insignificant in contrast to the actual computation.

**Comment by jcguu95** [comment]
Thank you for the fix!! It should make `py4cl` much much more robust as far as I concern.

The limit from stream communication is exactly what multiprocessing can achieve. Essentially it allows multiple communications to happen during roughly the same time. In your example,
```
(loop repeat 10000 do (py4cl2:pyeval "str(1)")))
```
The (N+1)th communication has to wait for the Nth communication, because that is a synchronous call. You can see the need of wait in the following form.
```
(loop repeat 5 do (py4cl2:pyexec "import time; time.sleep(0.2)") (format t ".") (terpri))
```

If we had `pyeval-async`, then the second communication does not have to wait for the first communication. Instead, the first form immediately returns (while the first communication hasn't ended), and then the second form gets evaluated (and so on). An immediate question is then, "What does the first form return?". Well, it returns a "handle" (called promise, in the async-io multithreading model) that can be later evaluated to the true answer provided by python. That means we can no longer write `(+ (pyeval-async 1) (pyeval-async 1))` because `#'+` doesn't know how to add to handles together. Instead, we need to wrap `#'+` so that it "learns" to also returns a handle, and so on. 

You can tell that this is not so easy to achieve. There's a nice write-up for how to do this for emacs-lisp [here](https://nullprogram.com/blog/2019/03/10/) with lisp macro. However, I'm no experts in this, and I cannot tell if that misses some important funcationality in async-io. We have an [async io lib for CL](https://github.com/orthecreedence/cl-async), but I have heard somewhere that it is also not "complete". Again, I really cannot judge.

Please let me know about your thoughts! I appreciate your work :)

**Comment by jcguu95** [comment]
With the help of [`lparallel`](https://lparallel.org/), a minimal example that almost works is the following. Please notice that since `pyeval` is still blocked, the it still takes roughly `5*2=10` seconds to complete. However, if we achieved 

1. each python call goes through a different named pipe (instead of the same default pipe)
2. python handle different requests during the same time (by using threads)

Then it should finish the computation in around `5` seconds.

```
(ql:quickload :lparallel)
(ql:quickload :py4cl2)

(defpackage :example
  (:use :cl :py4cl2)
  (:shadow :chain)
  (:use :lparallel))

(in-package :example)

(setf lparallel:*kernel* (lparallel:make-kernel 5))

(pyexec "import time")
(pyexec "def long_computation (x): time.sleep(5); return x")

(time
 (let* ((x (future (pyeval "long_computation(2)")))
        (y (future (pyeval "long_computation(3)"))))
   (* (force x) (force y))))

;; Evaluation took:
;;  10.079 seconds of real time
;;  0.004730 seconds of total run time (0.002021 user, 0.002709 system)
;;  0.24% CPU
;;  2 forms interpreted
;;  0 bytes consed
  
;; 6 (3 bits)
```

**Comment by digikar99** [comment]
As far as I see, there are two related issues here:

1. One is the race that arises when multiple lisp threads try sending data to the python process simultaneously. An example of this (moving to the commit ff41ea001a3a845fdc1b816c42a4d912b37c1730 before the lock):

```lisp
CL-USER> (py4cl2:pystop)
0
CL-USER> (py4cl2:pyexec "import time")
; No value
CL-USER> (dotimes (i 10)
           (bt:make-thread (lambda ()
                             (py4cl2:pyeval "str(1)"))))
```

This essentially results in garbage messages being sent, even though no "long computation" is involved; and hence the errors.

2. A second lisp thread trying to send data to the python process while the first thread has (i) finished sending data (ii) but hasn't received its output. If the first thread hadn't finished sending the data, it is the previous issue.

---

I actually doubt that the second is an issue, because input and output to the python processes are using different streams already. 

A lock helps in resolving the issues of the first, and no amount of multiprocessing on the python side will be helpful, *so long as the python process has a single point of input*. I guess, it is here that multiprocessing and named pipes could be helpful!

My contention to using multiprocessing is that it is generally employed to speed up computation, and in fact, that seems to be the use case here. And I feel a better means to speed up computation will be to 

1. Either speed up the interprocess communication - since a lot of the time is actually spent in the communication of the data itself, and this is almost 10 times as much `eval` in the worst case, which is already frowned upon
2. Or, to use a native-lisp or a C library. Both of these should play much nicer with multithreading. Something like [cl-autowrap](https://github.com/rpav/cl-autowrap) can be very much helpful!

If using multiprocessing in the python process still sounds like the good way forward for what you want to do, I'm okay with giving it a try as well as accepting PRs. Most probably, we will leave the existing `pyeval` and `pyexec` machinery untouched since I want it to be as bare as possible, and introduce a new message type that involves the creation of named-pipes/etc and the execution of code in the separate process through python's multiprocessing.

**Comment by jcguu95** [comment]
> As far as I see, there are two related issues here:

I agree. The first issue has been solved by introducing the lock (commit [482d4b0](https://github.com/digikar99/py4cl2/commit/482d4b0d589776235899ffc75c52a0e3bb9da314)), while the second was an issue because input and output use different pipes.

------

> .. to speed up computation

As you pointed out, the computation is slowed down because of I/O. Currently, the second call has to wait for the first call to finish, and the third call has to wait for the second call to finish, and so on.

To resolve this: If there are 3 requests to python, we need to call python 3 times **at almost the same time**. On the Lisp side, this can be done with

```
(time
 (plet ((x (pyeval "request 1"))
        (y (pyeval "request 2"))
        (z (pyeval "request 3")))
   (list x y z)))
```

There are two remaining points to be addressed.

1. We need to open 3 input pipes for these requests, as they will be fired at almost the same time. If we remain with one input pipe, python likely will get garbage message.
2. Python needs to handle 3 input at the same time (either use thrreads, asyncio, or similar technology). Otherwise, even if Lisp sends 3 requests at the same time, python will still take its time to send them back one by one.

---

> Most probably, we will leave the existing pyeval and pyexec machinery untouched since I want it to be as bare as possible.

Agree.

**Comment by digikar99** [comment]
> Currently, the second call has to wait for the first call to finish, and the third call has to wait for the second call to finish, and so on.

It is slow even if no such waiting times are involved:

```lisp
CL-USER> (py4cl2:pyexec "tot_time = 0")
; No value
CL-USER> (time
          (dotimes (i 10000)
            (py4cl2:pyexec "
import time;
start = time.time()
for i in range(1): str(i) # The larger this computation, the more insignificant is the time spent
tot_time += time.time()-start
")))
Evaluation took:
  2.568 seconds of real time
  1.083906 seconds of total run time (0.664687 user, 0.419219 system)
  42.21% CPU
  20,000 forms interpreted
  5,673,145,740 processor cycles
  14,192,176 bytes consed

NIL
CL-USER> (py4cl2:pyeval "tot_time")
0.05368804931640625d0

```

The time spent in the python process is itself just 0.05 seconds. The rest of the time is spent in actually getting the data to and from the python process. The following might be a useful illustration of what is happening in one python function call in py4cl2.

![image](https://user-images.githubusercontent.com/31390273/200638103-a3067da7-885d-459e-93ef-07b657033623.png)

Depending on if the actual computation is significant, implementing multiprocessing can be useful. Although if the actual computation is that intensive, one already expects python libraries to be using C under the hood and using multithreading, thus eliminating any benefit multiprocessing can achieve.

If the actual computation is insignificant, multiprocessing won't save much time.

---

I'm hoping to look into the multiprocessing approach in the week or month - in case you find a good way to do it in the meanwhile, feel free to issue a PR!

**Comment by jcguu95** [comment]
> feel free to issue a PR!

Thanks! I will see what I can do.

> If the actual computation is insignificant, multiprocessing
  won't save much time.

Please correct me if I'm wrong: I'm claiming that even if the
actual computation is insignificant, we still need
multiprocessing. This is because in your code

```
(dotimes (i 10000) (py4cl2:pyexec "insignificant computation")))
```

The second python call has to wait for the first python call to
return. And as you pointed out, even if the actual computation of
the first call is insignificant, the first *call* still takes a
while because it contains lisp->python and python->lisp
communication.

The multiprocessing approach would allow the second call be fired
before the first call returns.

**Comment by digikar99** [comment]
Yes multiprocessing will allow the second call to be fired before the first call returns, but the first call will still take just as long - you will gain in throughput (limited by the number of cores) but not in latency.

But by using lisp-native, or CFFI, or better interprocess communication in py4cl2, the gains are likely to be manifold in terms of both throughput and latency even on a single core.
