### ISSUE TITLE
DEFPYMODULE raises an error in (pyexec "import inspect")

### ISSUE THREAD

**Issue by rpgoldman** [digikar99/py4cl2#8]
When I try to execute this `defpymodule`:

  (defpymodule "registry_wrapper" t :lisp-package "RC")

on SBCL, I get this error:

```
Invalid number: "import inspect" [Reason: Multiple exponent-markers in number]
   [Condition of type ORG.MAPCAR.PARSE-NUMBER::INVALID-NUMBER]

Restarts:
 0: [RETRY] Retry SLY mREPL evaluation request.
 1: [ABORT] Return to sly-db level 1.
 2: [RETRY] Retry compiling #<CL-SOURCE-FILE "composition-example" "service-registry" "init-python">.
 3: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "composition-example" "service-registry" "init-python"> as having been successful.
 4: [RETRY] Retry ASDF operation.
 5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 --more--

Backtrace:
 0: ((FLET ORG.MAPCAR.PARSE-NUMBER::INVALID-NUMBER :IN ORG.MAPCAR.PARSE-NUMBER:PARSE-POSITIVE-REAL-NUMBER) "Multiple exponent-markers in number")
 1: (ORG.MAPCAR.PARSE-NUMBER:PARSE-POSITIVE-REAL-NUMBER "import inspect" :START 0 :END 14 :RADIX 10)
 2: ((LABELS PYTHONIZEP :IN "/Users/rpg/projects/logx-squid/composition-example/ql/dists/quicklisp/software/py4cl2-v2.6.0/src/callpython.lisp") "import inspect")
 3: ((LABELS PYTHONIZE-IF-NEEDED :IN "/Users/rpg/projects/logx-squid/composition-example/ql/dists/quicklisp/software/py4cl2-v2.6.0/src/callpython.lisp") "import inspect")
 4: (PYEXEC "import inspect")
 5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (PYEXEC "import inspect") #<NULL-LEXENV>)
 6: (EVAL (PYEXEC "import inspect"))
 7: ((LAMBDA NIL :IN SLYNK-MREPL::MREPL-EVAL-1))
 ```

For some reason `pythonize` seems to think that this string should be interpreted as a number.  Actually, I have no idea why `pythonize` is being called at all -- this argument is a string so shouldn't it simply be returned instead of being translated?

As an aside, it would be nice if `pythonize-if-needed` and `pythonize-p` were top-level functions instead of defined in `LABELS` -- having them be in `LABELS` means that I can't test them at the REPL unless I can figure out how to get into the lexical context where they are defined.

I can't figure out why this is happening because the definition of `pythonizep` should short-circuit evaluate this and not invoke `parse-number`.  Also, even if it *did* mistakenly invoke `parse-number`, why doesn't `ignore-errors` keep this from barfing?

Oh, I see why *that* is happening, anyway -- `invalid-number` is a *condition*, but it is *not* an error.  So `ignore-errors` does not trap this case. Ouch!

You probably need to fix the call to `parse-positive-real-number` to catch `invalid-number` and return nil.

This *might* be a fix:

```
(labels ((pythonizep (value)
           "Determines if VALUE should be pythonized."
           (or (not (stringp value)) ; do not pythonize if
               (ignore-errors (catch 'invalid-number
                                (handler-bind ((parse-number::invalid-number #'(lambda (x) (declare (ignore x))
                                                                                 (throw 'invalid-number nil))))
                                        (realp (parse-number:parse-number value)))))))
         (pythonize-if-needed (value)
           (if (pythonizep value) (pythonize value) value)))
```

But I would much prefer:

```
(defun pythonizep (value)
  "Determines if VALUE should be pythonized."
  (or (not (stringp value)) ; do not pythonize if
      (ignore-errors (catch 'invalid-number
                         (handler-bind ((parse-number::invalid-number #'(lambda (x)
                                                                                 (throw 'invalid-number nil))))
                            (realp (parse-number:parse-number value)))))))

(defun pythonize-if-needed (value)
   (if (pythonizep value) (pythonize value) value)))

```

**Comment by rpgoldman** [comment]
A quick follow-up -- it would be nice if `defpymodule` didn't perform its tasks at macroexpand time, but only at evaluation time.  It's harder to debug a macro-expansion than a block of code that is generated by a macroexpansion.

**Comment by digikar99** [comment]
> this argument is a string so shouldn't it simply be returned instead of being translated?

I went with this semantics, because

```lisp
CL-USER> (py4cl:python-eval 5)
5
CL-USER> (py4cl:python-eval "5")
5
```

Rethinking, one could do `(py4cl:python-eval "'5'")`, but, I'm not sure, that "5" should evaluate to a string feels more intuitive to me.

***

Re: invalid-number

For some strings (eg. `"math"`), on Linux, SBCL also raises `sb-int:simple-parse-error`; also, on Linux, SBCL `ignore-error` does catch `parse-number:invalid-number` - while this does correspond to a condition, it is raised by `error` in the body of `parse-number:parse-numer`. So, I'm unsure who exactly (SBCL on linux vs windows vs the code here) is wrong here corresponding to ANSI CL. Plus, my windows seems to be a bit messed up at the moment.

***

Re: labels

There's another `pythonize-if-needed` function below; but yeah, certainly, the two-three of the local functions can be renamed and made global.

***

A quick fix could be to replace `pyexec` (and `pyeval`? Haven't thought much yet; will need to check if any arguments need to be pythonized) in import-export.lisp with `raw-pyexec` (and `raw-pyeval`).

***

Re: `defpymodule` expansion during evaluation
 
The intended use case was that one'd simply define the python modules in a file similar to package.lisp (and I've certainly successfully used it that way) that is only ever long-run once. I could certainly make it respect `(debug 3)` to let the tasks take place during run-time.

***

Are there any recommendations for a VM for windows lisp development?

**Comment by rpgoldman** [comment]
I can't replicate this again -- seems like I must have gotten my python bridge into a bad state.  I'll close this issue and reopen if I hit it again.

I'll see about a PR for the de-labels-ing, but it's hard right now because I have a small team that are using cl4py2 from quicklisp, so changes threaten the stability of our project.
